global:
  variables:
  - RACK_ENV=test
  - SINATRA_ENV=test
  - DATABASE_URL=postgres://test:secret@localhost/todo-test
  - BUNDLE_PATH=vendor/bundle
  - LANG=C.UTF-8

tasks:
  test-with-compose:
    steps:
    - checkout
    - commands: 
      - docker-compose down
      - docker system prune -f
    - commands:
      - docker-compose build
      - docker-compose up -d    
    - run: docker-compose down
      when: always

  test:
    runner:
      os_image: ubuntu
      containers:
      - image: postgres
        environment:
        - POSTGRES_DB=todo-test
        - POSTGRES_USER=test
        - POSTGRES_PASSWORD=secret
    steps:
    - checkout
    - cache/pull:
        key: bundle-{{ checksum "Gemfile.lock" }}
    - commands:
      - rbenv local 3.1
      - ruby -v
      - bundle config set --local with $SINATRA_ENV 
      - bundle install
    - cache/push:
        key: bundle-{{ checksum "Gemfile.lock" }}
        paths:
        - vendor/bundle
    - commands:
      # wait for db
      - dockerize -wait tcp://localhost:5432
      # execute tests
      - bundle exec rake nuke_db
      - COVERAGE=true bundle exec rake spec
    # upload coverage report to dashboard (generated above)
    - reports/html:
        dir: coverage
        index: index.html # location of index file for preview
    - reports/junit:
        paths: [rspec.xml]
    - commands:
      ## use ruby-advisory DB for gems
      - bundle exec bundler-audit
