
tasks:
  # test-with-docker:
  #   steps:
  #   - checkout
  #   - commands: 
  #     - docker-compose down
  #     - docker system prune -f
  #   - commands:
  #     - docker-compose build
  #     - docker-compose up -d
      
  #     - docker-compose exec -T web dockerize -wait tcp://db:5432

  #     - docker-compose exec -T web rake nuke_db
  #     - docker-compose exec -T web bundle exec rspec
    
  #   - run: docker-compose down
  #     when: always
  
  test:
    cache:
    - key: ruby-sinatra-{{ checksum "Gemfile.lock" }}
      paths:
      - vendor/bundle
    steps:
    - checkout
    - commands: 
      - rbenv local 3.1.2
      - bundle check || bundle install
    # - commands:
    #   - bundle exec rake db:nuke_db
    #   - bundle exec rake spec
