global:
  variables:
  - RACK_ENV=test
  - RAILS_ENV=test
  - DATABASE_URL=postgres://localhost/todo-test

tasks:
  # test-with-docker:
  #   steps:
  #   - checkout
  #   - commands: 
  #     - docker-compose down
  #     - docker system prune -f
  #   - commands:
  #     - docker-compose build
  #     - docker-compose up -d
      
  #     - docker-compose exec -T web dockerize -wait tcp://db:5432

  #     - docker-compose exec -T web rake nuke_db
  #     - docker-compose exec -T web bundle exec rspec
    
  #   - run: docker-compose down
  #     when: always
  
  test:
    runner:
      os_image: ubuntu
      containers:
      - image: postgres # db service
        environment:
        - POSTGRES_DB=todo-test
    steps:
    - checkout
    - cache/pull:
        key: bundle-{{ checksum "Gemfile.lock" }}
        fallback_key: bundle-
    - commands:
      - rbenv versions
      - rbenv local 3.1.4
      - bundle check || bundle install
    - cache/push:
        key: bundle-{{ checksum "Gemfile.lock" }}
        paths:
        - vendor/bundle
    - commands:
      - dockerize -wait tcp://localhost:5432
      - bundle exec rake db:nuke_db
      - bundle exec rake spec
